const fn = (text: string, codes: Array<number>) => `\u001b[${codes[0]}m${text}\u001b[${codes[1]}m`;
export const codes = {
  bold: [1, 22],
  dim: [2, 22],
  italic: [3, 23],
  underline: [4, 24],
  inverse: [7, 27],
  hidden: [8, 28],
  strikethrough: [9, 29],

  black: [30, 39],
  red: [31, 39],
  green: [32, 39],
  yellow: [33, 39],
  blue: [34, 39],
  magenta: [35, 39],
  cyan: [36, 39],
  white: [37, 39],
  gray: [90, 39],
  grey: [90, 39],

  bgBlack: [40, 49],
  bgRed: [41, 49],
  bgGreen: [42, 49],
  bgYellow: [43, 49],
  bgBlue: [44, 49],
  bgMagenta: [45, 49],
  bgCyan: [46, 49],
  bgWhite: [47, 49],
};
export const colors = {
  reset: [0, 0],
  bold: text => fn(text, codes.bold),
  dim: text => fn(text, codes.dim),
  italic: text => fn(text, codes.italic),
  underline: text => fn(text, codes.underline),
  inverse: text => fn(text, codes.inverse),
  hidden: text => fn(text, codes.hidden),
  strikethrough: text => fn(text, codes.strikethrough),
  black: text => fn(text, codes.black),
  red: text => fn(text, codes.red),
  green: text => fn(text, codes.green),
  yellow: text => fn(text, codes.yellow),
  blue: text => fn(text, codes.blue),
  magenta: text => fn(text, codes.magenta),
  cyan: text => fn(text, codes.cyan),
  white: text => fn(text, codes.white),
  gray: text => fn(text, codes.gray),
  grey: text => fn(text, codes.grey),
  bgBlack: text => fn(text, codes.bgBlack),
  bgRed: text => fn(text, codes.bgRed),
  bgGreen: text => fn(text, codes.bgGreen),
  bgYellow: text => fn(text, codes.bgYellow),
  bgBlue: text => fn(text, codes.bgBlue),
  bgMagenta: text => fn(text, codes.bgMagenta),
  bgCyan: text => fn(text, codes.bgCyan),
  bgWhite: text => fn(text, codes.bgWhite),
};
